from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
import io


def generate_pdf_report(df, score, breakdown, insights):

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    elements = []
    styles = getSampleStyleSheet()

    income = df[df["transaction_type"] == "Income"]["amount"].sum()
    expense = df[df["transaction_type"] == "Expense"]["amount"].sum()
    savings = income - expense

    # --------------------------
    # Title Section
    # --------------------------
    elements.append(Paragraph("Personal Finance Intelligent System (PFIS)", styles["Title"]))
    elements.append(Spacer(1, 0.3 * inch))

    elements.append(Paragraph("Executive Financial Summary", styles["Heading1"]))
    elements.append(Spacer(1, 0.2 * inch))

    # --------------------------
    # Financial Summary
    # --------------------------
    elements.append(Paragraph(f"Total Income: ₹ {income:,.2f}", styles["Normal"]))
    elements.append(Paragraph(f"Total Expense: ₹ {expense:,.2f}", styles["Normal"]))
    elements.append(Paragraph(f"Net Savings: ₹ {savings:,.2f}", styles["Normal"]))
    elements.append(Spacer(1, 0.3 * inch))

    # --------------------------
    # Health Score
    # --------------------------
    elements.append(Paragraph(f"Financial Health Score: {score} / 100", styles["Heading2"]))
    elements.append(Spacer(1, 0.2 * inch))

    elements.append(Paragraph("Health Score Breakdown:", styles["Heading3"]))
    elements.append(Spacer(1, 0.15 * inch))

    # Safe access for breakdown keys
    savings_ratio = breakdown.get("Savings Ratio (%)", "N/A")
    large_ratio = breakdown.get("Large Transaction Ratio (%)", "N/A")
    anomaly_ratio = breakdown.get("Anomaly Ratio (%)", "N/A")
    concentration_ratio = breakdown.get("Top Category Concentration (%)", "N/A")

    elements.append(Paragraph(f"Savings Ratio: {savings_ratio}%", styles["Normal"]))
    elements.append(Paragraph(f"Large Transaction Ratio: {large_ratio}%", styles["Normal"]))
    elements.append(Paragraph(f"Anomaly Ratio: {anomaly_ratio}%", styles["Normal"]))
    elements.append(Paragraph(f"Top Category Concentration: {concentration_ratio}%", styles["Normal"]))
    elements.append(Spacer(1, 0.3 * inch))

    # --------------------------
    # Insights Section
    # --------------------------
    elements.append(Paragraph("Automated Financial Insights:", styles["Heading2"]))
    elements.append(Spacer(1, 0.2 * inch))

    if insights:
        for insight in insights:
            elements.append(Paragraph(f"- {insight}", styles["Normal"]))
            elements.append(Spacer(1, 0.15 * inch))
    else:
        elements.append(Paragraph("No insights available.", styles["Normal"]))

    elements.append(Spacer(1, 0.5 * inch))

    # --------------------------
    # Footer
    # --------------------------
    elements.append(Paragraph("Generated by PFIS | VH24", styles["Normal"]))

    doc.build(elements)

    buffer.seek(0)
    return buffer
